apiVersion: v2
description: >
  Helm chart for tala-agent
  capabilities for the Qlik.
name: tala-agent
version: 0.1.1
keywords:
  - tala-agent
home: https://www.qlik.com
sources:
  - https://github.com/qlik-trial/tala-agent
dependencies:
  - name: qlikcommon
    version: 3.26.2
    repository: oci://ghcr.io/qlik-trial/helm
    condition: global.component-common-imports
