{{- template "common.configmap" (list . "tala-agent.configmap") -}}
{{- define "tala-agent.configmap" -}}
{{- end }}

---
{{ template "common.secret" (list . "tala-agent.secret") -}}
{{- define "tala-agent.secret" -}}
{{- end }}
---

{{ template "common.serviceaccount" (list . "tala-agent.serviceaccount" ) -}}
{{- define "tala-agent.serviceaccount" -}}
{{- end }}

---
{{ template "common.networkpolicy" (list . "tala-agent.networkpolicy") -}}
{{- define "tala-agent.networkpolicy" -}}
{{- end }}

---
{{ template "common.sealedsecret" (list . "tala-agent.sealedsecret") -}}
{{- define "tala-agent.sealedsecret" -}}
{{- end }}

---

{{ template "common.service" (list . "tala-agent.service") -}}
{{- define "tala-agent.service" -}}
{{- end }}

---
{{ template "common.deployment" (list . "tala-agent.deployment") -}}
{{- define "tala-agent.deployment" -}}
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    qlik.encryption: "true"
  annotations:
    qlik.encryption.service: '{ "serviceS2SName": "tala-agent", "serviceDisplayName": "tala-agent", "serviceEncryptionContext": "tala-agent" }'
spec:
  template:
    spec:
      containers:
        -
{{ include "common.container" (list (set . "container" .Values.deployment.container) "tala-agent.deployment.container") | indent 8 }}
{{- end }}


{{- define "tala-agent.deployment.container" -}}
livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /ready
    port: http
ports:
  - name: http
    containerPort: {{ .Values.service.port }}
    protocol: TCP
{{- end }}
---
{{ template "common.keyrequest" (list . "tala-agent.keyrequest") -}}
{{- define "tala-agent.keyrequest" -}}
{{- end }}

---
{{ template "common.keyssecret" (list . "tala-agent.keyssecret") -}}
{{- define "tala-agent.keyssecret" -}}
{{- end }}

---
{{ template "common.hpa" (list . "tala-agent.hpa") -}}
{{- define "tala-agent.hpa" -}}
{{- end }}
