apiVersion: qlik.com/v1
kind: HelmChart
metadata:
  name: tala-agent
chartHome: ../chart
chartName: tala-agent
releaseName: tala-agent
releaseNamespace: $(NAMESPACE)
newChartVersion: $(VERSION)
values:
  image:
    tag: $(VERSION)
