apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/name: {{template-agent}}
resources:
  - helmchart.yaml
transformers:
  - fullpath.yaml
  - searchreplacetag.yaml
  - values.yaml
